### ISSUE TITLE
Forge Viewer not loading

### ISSUE THREAD

**Issue by e-hermoso** [e-hermoso/OCPW-Automation-Map-Check#14]
The drawing does not load inside the Viewer.  T

![Capture1](https://user-images.githubusercontent.com/24686706/160927673-f5ed23fc-6998-48cd-aec7-acb22cbe5e0f.JPG)

**Comment by kyle-durnford** [comment]
When this happens, it's an error with Autodesk Forge itself. One common issue is that there are too many calls and it can't process the current call. To remedy this issue, the app now attempts 3 calls 10 seconds apart if there is an error. If all 3 attempts fail, the user is prompted with text advising them to click to try again.
